- .gitignore
- src/server/serve.rs
The CORS filter requires an acceptable list of hosts that can call the endpoint. This needs to be configurable, esp due to local development, so moving this to an environment variable where the hosts are comma separated
e.g.
```
ALLOWED_FE_ORIGINS=http://google.com,https://localhost:4000
```
> Move FE origin values to env var

- src/gateway/auth.rs
- src/gateway/login.rs
- src/gateway/mod.rs
- src/server/serve.rs
- src/usecases/login.rs
The auth payload used to live in the post body, but for JWTs the canonical place for them to be received is in the header.
Also adding that the path now by
/login/google_id
so that the response of the login request is not dynamic on the header, except when it's authenticated vs unauthenticated.
> Auth payload into header

- Cargo.lock
- Cargo.toml
Temp (hopefully) shifting over to a fork of serde_dynamodb - keys with empty strings were not being serialized and this causes problems when fetched out as one giant blob later, since there would be missing keys and it would cause deserialization errors in the front end.
> Shifting over to fork of serde_dynamodb

- src/application/songs/dynamodb.rs
- src/application/songs/entity.rs
- src/application/songs/gateway.rs
- src/application/songs/usecase.rs
- src/application/users/gateway.rs
- src/application/users/usecase.rs
- src/server/mod.rs
- src/server/users.rs
Allow collecting all songs for users and returning them - i.e. the catalog of songs that this user has worked on.
They are returned in the form of summary - all the metadata about the song but none of its actual contents (chords/lyrics), to encourage fetching of the song fresh and not caching the song for a cleaner paradigm.
> Getting all songs for users

- src/application/songs/gateway.rs
- src/application/songs/usecase.rs
C/P'd from the comments:
// prevent overwriting a more recent save if the last saved at timestamp is greater than the current one
// example:
// A --> B
//   \----->C
//
// Suppose I open the song at time A on two computers, make edits on both somewhat absentmindedly
// I first save at time B - the payload for the song for the last saved at would be A
// presume this succeeds, the server copy is now from time B and its last saved at time is also B
//
// Now I save another copy at time C, but the predecessor of my copy at time C was from A
// If I just go with last write wins, then all changes from the copy at time B would be overwritten
// So by comparing the timestamp at the save at C (A vs B), the save will fail to protect overwriting data.
//
// The user can then refetch the copy at …
> Protect against song overwriting

- src/application/songs/entity.rs
- src/application/songs/usecase.rs
When time is captured in the rust server, it's captured to the nanosecond level - however when it's sent to the browser, the browser only captures it to the millisecond level.
So when the browser roundtrip sends the data back to the server, the time now looks like it's (albeit tiny bit) before the time that was sent.
This change truncates the time resolution so that all involved components have an accurate (but imprecise) understanding of what time is.
> Fix overwriting usecase time gating

- Cargo.lock
- Cargo.toml
- src/application/concerns/gateway/errors.rs
- src/application/concerns/gateway/mod.rs
- src/application/songs/gateway.rs
- src/application/users/gateway.rs
Return all errors in the format of
{
msg: string,
code: string,
}
the important part being the code - for the same code the client can always handle it the same way, where as the msg returns a more human readable component
> Structured client errors

- src/application/concerns/gateway/errors.rs
- src/application/songs/gateway.rs
Serde's auto PascalCase to camel_case means that the code for UpdateSongWrongID == update_song_wrong_i_d which is counterintuitive, so working around that.
> Fix casing for UpdateSongWrongId code

- src/application/songs/tracks/usecase.rs
Adding some more detailed logging for errors that happen when publishing messages fail. This happens randomly and we need a bit more understanding around why.
> Log more error details for RabbitMQ publish error

- Dockerfile
fixed rust version to 1.55.0, the last version of Rust 2018
> anchor rust version in builder to fix runtime fail

- go-rewrite/src/server.go
- src/main.rs
Before this, in development, Rust server runs on 5000 and Go server runs on 5001. Swapping it to be such that Rust runs on 5001 and Go runs on 5000, so that the Go server is the "default" thing to point to.
> Swap development ports

- Makefile
- db_dump/Songs/data/0001.json
- db_dump/Songs/schema.json
- db_dump/TrackLists/data/0001.json
- db_dump/TrackLists/schema.json
- go-rewrite/src/server.go
Setting a region for local use - this will allow concurrent use of a local instance of dynamodb for development and testing in the future.
The convention is that the region for development is "localhost". dynamodump puts it in this region even though it's nowhere specified that the region is that.
In addition, making a prod backup.
> Local env: changes to dynamo region

- go-rewrite/src/errors/gateway/errors.go
- go-rewrite/src/lib/testing/song.go
- go-rewrite/src/server.go
- go-rewrite/src/song/entity/song.go
- go-rewrite/src/song/errors/errors.go
- go-rewrite/src/song/gateway/gateway.go
- go-rewrite/src/song/song_test.go
- go-rewrite/src/song/storage/db.go
- go-rewrite/src/song/usecase/usecase.go
- go-rewrite/src/track/gateway/gateway.go
- go-rewrite/src/track/storage/db.go
- go-rewrite/src/track/usecase/usecase.go
The update song endpoint.
A couple of changes from the original Rust implementation:
-the id and owner field is ensured to be the same as the DB copy instead of throwing an error
-UUIDs are not parsed anywhere, if an ID is not a UUID, just let it be caught as not found at the DB level. however empty strings need to be fenced at the DB level.
> Go rewrite: update song endpoint

- .github/workflows/docker-image.yml
- .github/workflows/go-docker-image.yml
remove image prune (no longer needed)
> docker image prune no longer needed as runners are now ephemeral

- server/Dockerfile
- worker/Dockerfile
changing the dockerfile commands again. I think the issue was that the relative path from the go mod file must be respected, so worker and server sources must also be in that relative path structure, and can't be hoisted up one level.
> change dockerfile once more

- worker/src/internal/application/jobs/transfer/download/youtubedl.go
Youtube-dl is getting a 403. This is what stackoverflow says to do. We'll see how it goes.
> Fix: Track fetching results in 403

- worker/src/internal/application/jobs/transfer/download/youtubedl.go
Referencing https://github.com/veedubyou/chord-paper-be/pull/117
Cache clearing on every download might be too aggressive - try doing this only if a failure happens. In the future, maybe try to find a way to detect the 403.
> Conditionally clear youtubedl cache

- .github/workflows/build-and-test.yml
- src/server/application/app.go
- src/server/internal/track/track_test.go
- src/server/internal/track/usecase/usecase.go
- src/shared/lib/rabbitmq/publish.go
- src/shared/testing/rabbitmq.go
- src/worker/application/app.go
Adding a retry path - on occasion RabbitMQ would lose the connection. Attempting to see if just reconnecting would help blow away this whole class of publishing connection errors.
> Reconnect and retry for queue publishing failures

- src/server/application/app.go
- src/server/internal/track/track_test.go
- src/shared/lib/rabbitmq/publish.go
- src/worker/application/app.go
RabbitMQ can be down for various reasons. We can just shoot an error at the time of publish (as well as establishing the connection on the fly) - prevent this from blocking BE from starting the rest of it by taking out the error condition in the beginning.
> Don't block BE from starting if RabbitMQ is down

- docker/youtube-dl/Dockerfile
- src/worker/worker.go
Youtube-dl is dragging its feet fixing its releases. It's broken right now and cannot be used for youtube. Switching to yt-dlp for now
> Switch to yt-dlp

- .github/workflows/worker-prod-deploy.yml
apparently when the youtube-dl workflow was written, it was never updated to have kubernetes set the initContainer's image as well, so the only time the youtube-dl's container was updated was when the deployment was restarted manually.  Now the workflow has been updated to update the youtube-dl's container as well.
> change image of youtube-dl container as well

- Makefile
- src/shared/integration_test/track_split/track_split_test.go
- src/shared/track/entity/track.go
- src/worker/internal/application/jobs/split/splitter/file_splitter/local_splitter.go
Demucs FT is too resource intensive to use for real. It's also not worth the wait, so removing this.
> Remove demucs-ft support
