src/server/serve.rs

Due to cross origin, each path must be configured to handle CORS properly.......i guess. Do all other web servers have to do this?

Add handling of CORS preflight

---

src/server/serve.rs

Reverts veedubyou/chord-paper-be#13

Revert "rip"

---

.idea/runConfigurations/Run_chord_paper_be.xml
.k8s/deploy.yml
src/db_utils/dynamodb.rs
src/server/serve.rs
src/server/users.rs
src/users/dynamodb.rs
src/users/gateway.rs
src/users/mod.rs
src/users/usecase.rs

Integrating dynamo to the app
Introduces invisible dependency of needing env vars
AWSAccessKeyId
AWSSecretKey
These can just be set to "local" for local development.
This change will cause user data to be created in the users table upon login.

Adding User DB

---

src/application/songs/usecase.rs

Validate ID as UUID before hitting the data store

---

src/server/songs.rs

just being more restfully restful

Use PUT verb instead of POST verb for update

---

Cargo.lock
Cargo.toml
src/application/songs/entity.rs
src/application/songs/usecase.rs

Upon any write, attach a "last saved at" date. This prevents overwriting songs in a multi device scenario (that feature to soon follow).

adding last saved at on save

---

.github/workflows/docker-image.yml
.github/workflows/pr-build.yml

change workflows back to being self hosted

resuming self hostedness

---

src/application/songs/tracks/usecase.rs

Update published job name

---

src/application/songs/songs/dynamodb.rs
src/application/songs/songs/gateway.rs
src/application/songs/songs/usecase.rs
src/server/songs.rs

Adding the DELETE verb for the song so that it can be removed.

Delete song endpoint

---

.gitignore
db_dump/Songs/data/0001.json
db_dump/Songs/schema.json
db_dump/TrackLists/data/0001.json
db_dump/TrackLists/schema.json
src/application/songs/tracks/entity.rs
src/application/songs/tracks/usecase.rs

Together with https://github.com/veedubyou/chord-paper-be-workers/pull/23 and veedubyou/chord-paper-fe#284
Adding job status to split track requests - this allows job errors to be reported back to the user.

Adding job status

---

src/application/songs/tracks/entity.rs

Together with https://github.com/veedubyou/chord-paper-fe/pull/285 and https://github.com/veedubyou/chord-paper-be-workers/pull/24
Supports job progress in split stem jobs.

Support job progress

---

.github/workflows/docker-image.yml
.github/workflows/pr-build.yml

Preparing for a go rewrite in this repo, so making PR jobs and deployments only happen for when Rust source has been modified.

Scope build requests for Rust source

---

.github/workflows/runner.yml
Dockerfile

remove :latest from runner.yml as well

Anchor rust version

---

go-rewrite/src/lib/request/ctx.go
go-rewrite/src/server.go
go-rewrite/src/song/gateway/gateway.go
go-rewrite/src/song/storage/db.go
go-rewrite/src/song/storage/errors.go
go-rewrite/src/song/usecase/usecase.go

Endpoint for deleting the song

Go rewrite: Delete song endpoint

---

.github/workflows/server-prod-deploy.yml

Adding the requirement that deploys only happen after tests and compilation passes

Prevent deploy until tests and compile pass

---

.github/workflows/server-pr.yml
.github/workflows/server-prod-deploy.yml

Just rejiggering it until it feels right

Rename github workflow jobs once more

---

.github/workflows/server-prod-deploy.yml
.github/workflows/worker-prod-deploy.yml
worker/Dockerfile

1) fix dockerfile for worker
2) add dependency for build/test for worker deploy flow

Fix Deploys

---

server/Dockerfile
worker/Dockerfile

These were pointing to the wrong locations. Fixing them.

Dockerfile changes for go mod

---

go.mod
go.sum
worker/src/internal/application/app.go
worker/src/internal/application/integration_test/dummy/rabbitmq.go
worker/src/internal/application/integration_test/integration_test_test.go
worker/src/internal/application/jobs/job_router/job_router_test.go
worker/src/internal/application/jobs/job_router/router.go
worker/src/internal/application/publish/publisher.go
worker/src/internal/application/publish/publishfakes/fake_publisher.go
worker/src/internal/application/worker/worker.go
worker/src/internal/sender/main.go

Removing the older amqp library and have both server and worker use the same one.

Consolidate amqp library

---

server/Dockerfile
worker/Dockerfile

Forgot to add this on. May reconsider the entire file tree though.

Add shared lib to dockerfile

---

src/worker/internal/application/app.go
src/worker/internal/application/integration_test/dummy/track_store.go
src/worker/internal/application/integration_test/integration_test_test.go
src/worker/internal/application/jobs/job_router/job_router_test.go
src/worker/internal/application/jobs/job_router/router.go
src/worker/internal/application/jobs/save_stems_to_db/handler.go
src/worker/internal/application/jobs/split/handler.go
src/worker/internal/application/jobs/split/split_test.go
src/worker/internal/application/jobs/split/splitter/file_splitter/local_splitter.go
src/worker/internal/application/jobs/split/splitter/file_splitter/remote_splitter.go
src/worker/internal/application/jobs/split/splitter/track_splitter.go
src/worker/internal/application/jobs/start/handler.go
src/worker/internal/application/jobs/transfer/download_test.go
src/worker/internal/application/jobs/transfer/track_downloader.go
src/worker/internal/application/tracks/store/dynamodb.go
src/worker/internal/application/worker/worker.go

Somehow during the IDE refactoring, a bunch of package2 aliases got added. Removing those.

Remove unnecessary package aliases

---

.gitignore
Makefile

Put local.envrc in the gitignore so that each dev can change it without affecting git status.

Omit local envrc

---

.github/workflows/server-build-and-test.yml
.github/workflows/split-track-test.yml
.github/workflows/worker-build-and-test.yml

Workflows: new setup go and cache

---

src/server/internal/song/song_test.go
src/server/internal/track/track_test.go
src/shared/integration_test/track_split/track_split_test.go

Turns out the By clauses have a body that could be filled in, this organizes the test code a bit nicer.

Filling in By's in ginkgo tests

---

.github/workflows/worker-prod-deploy.yml

Fixing worker prod deploy workflow

---

.github/workflows/server-prod-deploy.yml
.github/workflows/worker-prod-deploy.yml

run workflow when anything in the workflow files change.

Yt dlp workflow

---

src/shared/restart.txt

BE restart file

---

docker/worker/Dockerfile

Preparing dependency for a new feature

Add syncedlyrics to dockerfile

---

docker/server/Dockerfile
docker/worker/Dockerfile

Actually it should be over here...

Syncedlyrics on server

---

.k8s/worker/deploy.yml

add DEMUCS_BIN_PATH and DEMUCS_WORKING_DIR_PATH

k8s vars for demucs
